# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Cloud Functions Deploy
description: |-
  Use this action to deploy your function or
  update an existing Cloud Function.
author: Google LLC

inputs:
  credentials:
    description: |-
      (DEPRECATED) Optional service account key to use for authentication to
      GCP. This should be the JSON formatted private key which can be exported
      from the Cloud Console. The value can be raw or base64-encoded.
    required: false

  name:
    description: |-
      Name of the Cloud Function.
    required: true

  description:
    description: |-
      Description for the Cloud Function.
    required: false

  project_id:
    description: |-
      ID of the project in which to deploy the Cloud Function.
    required: false

  region:
    description: |-
      Region to deploy the function in. Defaults to us-central1, if not specified.
    default: 'us-central1'
    required: false

  source_dir:
    description: |-
      Path to function deployment directory within the source repo.
    default: './'
    required: false

  env_vars:
    description: |-
      List of key-value pairs to set as environment variables in the form KEY1=VALUE1,KEY2=VALUE2. Only one of env_vars or env_vars_file can be specified.
    required: false

  env_vars_file:
    description: |-
      Path to a local YAML file with definitions for all environment variables. Only one of env_vars or env_vars_file can be specified.
    required: false

  labels:
    description: |-
      List of key-value pairs to set as function labels in the form label1=VALUE1,label2=VALUE2.
    required: false

  entry_point:
    description: |-
      Name of a function (as defined in source code) that will be executed. Defaults to the resource name suffix, if not specified.
    required: false

  runtime:
    description: |-
      Runtime to use for the function.
    required: true

  memory_mb:
    description: |-
      The amount of memory in MB available for a function. Defaults to 256MB.
    required: false

  vpc_connector:
    description: |-
      The VPC Access connector that the function can connect to.
    required: false

  vpc_connector_egress_settings:
    description: |-
      The egress settings for the connector, controlling what traffic is diverted through it.
    required: false

  ingress_settings:
    description: |-
      The ingress settings for the function, controlling what traffic can reach it.
    required: false

  service_account_email:
    description: |-
      The email address of the IAM service account associated with the function at runtime.
    required: false

  timeout:
    description: |-
      The function execution timeout.
    required: false

  max_instances:
    description: |-
      The maximum number of instances for the function.
    required: false

  event_trigger_type:
    description: |-
      Specifies which action should trigger the function.
    required: false

  event_trigger_resource:
    description: |-
      Specifies which resource from eventTrigger is observed.
    required: false

  event_trigger_service:
    description: |-
      The hostname of the service that should be observed.
    required: false

  deploy_timeout:
    description: |-
      The function deployment timeout in seconds.
    default: 300
    required: false

outputs:
  url:
    description: The URL of your Cloud Function. Only available with HTTP Trigger.
  id:
    description: |-
      Full resource name of the Cloud Function, of the format
      'projects/p/locations/l/functions/f'.
  status:
    description: |-
      Status of the Cloud Function deployment.
  version:
    description: |-
      Version of the Cloud Function deployment.
  runtime:
    description: |-
      Runtime of the Cloud Function deployment.

runs:
  using: 'node12'
  main: 'dist/index.js'
