name: 'Cleanup'

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  cleanup:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: 'actions/checkout@v3'

    - uses: 'google-github-actions/auth@main'
      with:
        workload_identity_provider: '${{ secrets.WIF_PROVIDER_NAME }}'
        service_account: '${{ secrets.SERVICE_ACCOUNT_EMAIL }}'

    - uses: 'google-github-actions/setup-gcloud@main'

    - name: Delete services
      run: |-
        gcloud config set core/project "${{ secrets.PROJECT_ID }}"
        gcloud config set functions/region "us-central1"

        # List and delete all functions that were deployed 30 minutes ago or
        # earlier. The date math here is a little weird, but we're looking for
        # deployments "earlier than" 30 minutes ago, so it's less than since
        # time increases.
        (IFS=$'\n'; for NAME in $(gcloud functions list --format="value(name)" --filter="updateTime < '-pt30m'"); do
          echo "Deleting ${NAME}..."
          gcloud functions delete ${NAME} --quiet
        done)
