name: 'Release'

on:
  push:
    branches:
      - 'main'
      - 'release/**/*'

jobs:
  release:
    if: |-
      startsWith(github.event.head_commit.message, 'Release: v')
    name: 'Release'
    uses: 'google-github-actions/.github/.github/workflows/release.yml@v0' # ratchet:exclude

  publish:
    if: |-
      startsWith(github.event.head_commit.message, 'Release: v')
    runs-on: 'ubuntu-latest'
    needs: 'release'
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871' # ratchet:actions/checkout@v4

      - name: 'Publish'
        id: 'publish'
        uses: 'actions/publish-immutable-action@4b1aa5c1cde5fedc80d52746c9546cb5560e5f53' # ratchet:actions/publish-immutable-action@v0.0.3
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
