name: 'Unit'

on:
  push:
    branches:
      - 'main'
      - 'release/**/*'
  pull_request:
    branches:
      - 'main'
      - 'release/**/*'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  unit:
    permissions:
      contents: 'read'
      id-token: 'write'

    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-latest'
          - 'windows-latest'
          - 'macos-latest'
    runs-on: '${{ matrix.os }}'

    steps:
      - uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # ratchet:actions/checkout@v4

      - uses: 'actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a' # ratchet:actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: 'npm build'
        run: 'npm ci && npm run build'

      - name: 'npm lint'
        # There's no need to run the linter for each operating system, since it
        # will find the same thing 3x and clog up the PR review.
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: 'npm run lint'

      - id: 'auth'
        uses: 'google-github-actions/auth@v2' # ratchet:exclude
        if: ${{ github.event_name == 'push' || github.repository == github.event.pull_request.head.repo.full_name && github.actor != 'dependabot[bot]' }}
        with:
          project_id: '${{ vars.PROJECT_ID }}'
          workload_identity_provider: '${{ vars.WIF_PROVIDER_NAME }}'

      - name: 'npm test'
        env:
          TEST_AUTHENTICATED: '${{ !!steps.auth.outputs.auth_token }}'
          TEST_PROJECT_ID: '${{ vars.PROJECT_ID }}'
          TEST_SERVICE_ACCOUNT_EMAIL: '${{ vars.SERVICE_ACCOUNT_EMAIL }}'
          TEST_SECRET_VERSION_NAME: '${{ vars.SECRET_VERSION_NAME }}'
        run: 'npm run test'
