name: 'unit'

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  unit:
    name: 'unit'
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
        - 'ubuntu-latest'
        - 'windows-latest'
        - 'macos-latest'

    steps:
    - uses: 'actions/checkout@v2'

    - uses: 'actions/setup-node@v2'
      with:
        node-version: '12.x'

    - name: 'npm build'
      run: 'npm ci && npm run build'

    - name: 'npm lint'
      run: 'npm run lint'

    - name: 'npm test'
      env:
        DEPLOY_CF_SA_KEY_JSON: '${{ secrets.DEPLOY_CF_SA_KEY_JSON }}'
        GCLOUD_PROJECT: '${{ secrets.DEPLOY_CF_PROJECT_ID }}'
        DEPLOY_CF_EVENT_PUBSUB_TOPIC: '${{ secrets.DEPLOY_CF_EVENT_PUBSUB_TOPIC }}'
      run: 'npm run test'
